"""Rebuild the website's per-user PDF index after adding or removing files."""
import argparse
import json
from pathlib import Path
import re

DEFAULT_OUTPUT = Path(__file__).resolve().parents[2] / 'prayer'


def write_index(folder):
    from generate import atomic_write
    folder = Path(folder)
    weeks = {}
    for user in sorted(folder.iterdir()):
        if not user.is_dir():
            continue
        available = set()
        for pdf in user.iterdir():
            match = re.fullmatch(r'Nädal ([1-9][0-9]*)\.pdf', pdf.name)
            if pdf.is_file() and match:
                available.add(int(match[1]))
        weeks[user.name] = sorted(available, reverse=True)
    content = '// Generated by tools/prayer-generator/update_index.py.\n'
    content += 'window.BJK_PRAYER_WEEKS = ' + json.dumps(weeks, ensure_ascii=True, indent=2) + ';\n'
    atomic_write(folder / 'available-weeks.js', content.encode('utf-8'))
    return weeks


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    write_index(args.output)
    print(f'Updated {args.output / "available-weeks.js"}')
